### ISSUE TITLE
No cargar los videos de instrucciones al iniciar

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#12]
Para disminuir los tiempos de carga y la cantidad de videos que se muestran al inicio del juego, se deben ocultar los videos de instrucciones que se están desplegando automáticamente. En su lugar, mostrar:

- Al cargar, después del splash, únicamente el video de la historia de Congo y Quima
- Al verse la página de inicio la primera vez, colocar la flecha moviendose y apuntando al botón de Jugar
- Al entrar a la pantalla de niveles, la flecha apuntando al botón de la ayuda
- Al entrar al primer nivel, la flecha apuntando al botón de jugar el primer reto
- Al iniciar cada reto de los primeros 4, se debe poner la flecha apuntando al botón de la ayuda hasta que la persona haga cualquier acción

**Comment by jesusoterove** [comment]
Task completed
