### ISSUE TITLE
[N1-R3] No se visualizan las áreas de selección donde deberían

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#15]
En el reto 3 del nivel 1, no se están visualizando las áreas de selección en el lugar adecuado. En algunos casos se desbordan de la imagen y en otros no aparecen.
Probado en una tablet, con Android 5.1.1.
Adjunto imágenes donde se muestra el error.
![screenshot_2017-12-20-11-53-28](https://user-images.githubusercontent.com/6455806/34220548-00d41366-e583-11e7-8832-466a73bbf6ec.png)
![screenshot_2017-12-20-11-52-17](https://user-images.githubusercontent.com/6455806/34220549-00ee6ef0-e583-11e7-905f-e686ebc0e9b2.png)

**Comment by jesusoterove** [comment]
Closed with pull request #17
