### ISSUE TITLE
[N1-R3] Áreas de selección en tarjetas

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#16]
En las tarjetas, el área de selección debe abarcar únicamente la parte que contiene el teléfono. En los casos donde el teléfono haga parte de un párrafo, como por ejemplo en la carta del abuelo, el teléfono debe ser un área de selección y las líneas sobre él deben ser cada una un área de selección. Se adjunta una imagen que muestra más o menos cómo deberían ser las zonas de selección.

![tarjeta_abuelo](https://user-images.githubusercontent.com/6455806/34242768-5e715d36-e5eb-11e7-86f7-1b57989b5fe1.png)

**Comment by jesusoterove** [comment]
Bueno, no desglose de esa manera tan detallada las areas por que me parecía que quedaban demasiado pequeñas y difíciles de seleccionar con un toque. Sí se considera necesario cambiarlas, puedo hacerlo siempre que me pasen las coordenadas de las areas que se quieren marcar. El formato para la definición de areas 'marcables' en una imagen está compartido en este enlace:

id|esareacorrecta?|tipoarea|coordenadas

id: El consecutivo de la imagen (si la imagen se llama bg_card1.png, el id es 1)
esareacorrecta?: true si esta es un area válida, false en caso contrario
tipoarea: El tipo de area a demarcar, puede ser circle (Circulo), rect (Rectangulo paralelo al plano cartesiano) o poly (Rectangulo no paralelo al plano cartesiano o cualquier otro poligono).

coordenadas: Las coordenadas del area en el siguiente formato segun el tipo de area, todas las medidas son en pixeles
  circle: x,y,radio
    x,y: Representan el centro del circulo
    radio: el radio del circulo en pixeles
    Ejemplo: Un circulo de radio 201, con centro en 1295, 676
      1295,676,201
  
  rect:x,y,ancho,alto
    x,y: representan la esquina superior izquierda del rectangulo
    ancho: El ancho del rectangulo en pixeles
    alto: El alto del rectangulo en pixeles
    Ejemplo: Un rectangulo cuya esquina superior izquierda está en 1133, 371 y tiene 356 de ancho por 73 de alto
      1133,371,356,73
  
  poly: x1,y1,x2,y2...xn,yn
    xn,yn: Representan cada punto que forma el area a seleccionar. Se trazarán líneas para unir cada punto con el siguiente en la lista y al final se trazará una linea entre el último punto y el primero.
    Ejemplo: Area rentangular, se definen 4 puntos
      825,322,1205,276,1223,431,843,477    

Ejemplos:

1|false|poly|825,322,1205,276,1223,431,843,477
1|true|poly|519,934,947,884,961,1003,534,1053
2|false|rect|467,371,659,73
2|true|rect|1133,371,356,73
2|false|circle|1295,676,201
3|true|rect|464,358,552,198

**Comment by davidherney** [comment]
No se realizan cambios a la actividad, se dejan las zonas marcadas inicialmente.
