### ISSUE TITLE
Indicar con un efecto que se activó un botón

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#19]
En toda la aplicación, se precisa indicar con un efecto que se presionó un botón y se está iniciando la acción. Los efectos sugeridos son:
- Poner un alfa de 0.7 al botón o
- Hacer cambio del tamaño del botón sin que los demás elementos de la interfaz se muevan

Ese efecto también se precisa para las activides que sean de presionar algo, como la de "clasificación"

**Comment by jesusoterove** [comment]
Included in pull request #27
