### ISSUE TITLE
[N1-R6] Corregir salto al seleccionar una respuesta

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#25]
Cuando se selecciona una opción de las respuestas, la palabra se baja al parecer porque cambian los bordes que muestran si es correcta o incorrecta. Eso pasa en este reto y los siguientes que son similares. La idea es que la palabra conserve su posición aún cuando se marca si está o no correctamente seleccionada.

**Comment by jesusoterove** [comment]
Fixed with pull request #27
