### ISSUE TITLE
"Acerda de"

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#30]
Colocar en el botón de la aplicación los siguientes créditos:

**"Congo y Quima, un reto por la alfabetización"** es una aplicación de la Gobernación de Antioquia, desarrollada por la Facultad de Educación de la Universidad de Antioquia.

**Versión de la aplicación**
1.0.11

**Asesoría pedagógica**
Diana Milena Ruiz
Donna Zapata
Hilda Mar Rodríguez 

**Elaboración de contenidos**
Hilda Mar Rodríguez
Leidy Johana Rivillas

**Diseño gráfico**
David Castaño
Juliana Tobón
Sebastián Quintero

**Producción audiovisual**
David Castaño
Eliana Tamayo

**Comunicación y difusión**
Betsy Valencia 

**Corrección de estilo**
Juan Fernando Saldarriaga

**Desarrollo**
David Herney Bernal 
Jesús María Otero 

**Soporte metodológico**
Wilmer Gil
 
**Línea creativa**
Sebastián Guzmán 

**Voces**
Alejandra Valencia
Jhon Jairo Rincón

**Coordinación general**
Donna Zapata

**Coordinación de producción**
David Herney Bernal

**Producción ejecutiva**
Diana Milena Ruiz

**Licencia**
El código fuente de la aplicación se libera bajo licencia GNU/GPL versión 3 y se encuentra disponible en https://github.com/bambuco/congoyquima/.
Lo demás, está bajo una Licencia Creative Commons Atribución 4.0 Internacional. 

**Producción**
Gobernación de Antioquia

Facultad de Educación
Universidad de Antioquia

Medellín - Colombia

2017

**Comment by jesusoterove** [comment]
Closed with PR #43
