### ISSUE TITLE
[N1-R10] Problemas con la posición de los elementos

### ISSUE THREAD

**Issue by davidherney** [bambuco/congoyquima#32]
Las letras a arrastrar se están posicionando por debajo de las celdas "destino" y cuando se empiezan a mover algunas suben pero en algunos casos hay brincos pasando más abajo las que están en la parte superior, como distribuyendo el espacio. 

Ver ejemplos adjuntos:
![screenshot_2018-01-16-11-20-00](https://user-images.githubusercontent.com/6455806/34999642-4326c668-fab0-11e7-8d6a-998d83245a12.png)
![screenshot_2018-01-16-11-22-12](https://user-images.githubusercontent.com/6455806/34999643-43501fa4-fab0-11e7-8fff-ba1bc9f907c3.png)

**Comment by jesusoterove** [comment]
Closed with PR #43
